### ISSUE TITLE
how to calculate percentage

### ISSUE THREAD

**Issue by Mickey248** [PyThaiNLP/thai-sentiment-analysis#2]
Is there a way to predict and think of it as a percentage?
For example, predict("ฉันเกลียดคุณ")
Will get {'label': 'neg', 'score': 0.72400962114334106}.
Can you show it?
thank you very much

**Comment by wannaphong** [comment]
I used `nltk.classify.accuracy`. https://www.nltk.org/_modules/nltk/classify/util.html#accuracy

> accuracy = sum(correct) / len(correct)
